import uuid
from datetime import datetime, timezone
from sqlalchemy import select
from app.core.security import get_password_hash
from app.db.session import async_session_factory
from app.models.user import User
from app.models.campaign import Campaign
from app.models.influencer import Influencer
from app.models.contract import Contract
from app.models.approval import Approval
from app.models.agent_run import Agent, TimelineEvent
from app.models.outreach import OutreachMessage


async def seed_database():
    """Seed initial demo data if database is empty."""
    async with async_session_factory() as db:
        # Check if users already exist
        res = await db.execute(select(User).limit(1))
        if res.scalar_one_or_none() is not None:
            return  # Already seeded

        print("Seeding initial database data...")

        # 1. Demo User
        demo_user = User(
            id=uuid.UUID("11111111-1111-1111-1111-111111111111"),
            full_name="Aaditya Sharma",
            email="aaditya@glownaturals.com",
            password_hash=get_password_hash("password123"),
            company_name="GlowNaturals",
            role="marketing_manager",
            is_active=True,
            last_login_at=datetime.now(timezone.utc),
        )
        db.add(demo_user)
        await db.flush()

        # 2. Campaigns
        campaigns_data = [
            Campaign(
                id="camp-1",
                owner_id=demo_user.id,
                name="GlowNaturals Summer Launch",
                brand="GlowNaturals",
                status="active",
                health="excellent",
                budget=200000,
                spend=128000,
                revenue=392000,
                roas=3.06,
                influencers=8,
                progress=64,
                start_date="2026-08-20",
                end_date="2026-09-20",
                conversions=426,
                reach=1800000,
                objective="Product Launch",
                description="Summer skincare and hydration launch across micro and mid-tier creators.",
            ),
            Campaign(
                id="camp-2",
                owner_id=demo_user.id,
                name="Vitamin C Serum Awareness",
                brand="GlowNaturals",
                status="active",
                health="healthy",
                budget=150000,
                spend=98000,
                revenue=245000,
                roas=2.5,
                influencers=6,
                progress=72,
                start_date="2026-07-15",
                end_date="2026-09-15",
                conversions=312,
                reach=1200000,
                objective="Awareness",
                description="Educational campaign highlighting Vitamin C benefits for radiant skin.",
            ),
            Campaign(
                id="camp-3",
                owner_id=demo_user.id,
                name="Festive Glow Collection",
                brand="GlowNaturals",
                status="active",
                health="healthy",
                budget=180000,
                spend=45000,
                revenue=89000,
                roas=1.98,
                influencers=5,
                progress=28,
                start_date="2026-09-01",
                end_date="2026-10-15",
                conversions=98,
                reach=420000,
                objective="Conversions",
                description="Festive gifting bundles and limited edition glow kits.",
            ),
            Campaign(
                id="camp-4",
                owner_id=demo_user.id,
                name="Clean Beauty UGC Drive",
                brand="GlowNaturals",
                status="active",
                health="needs_attention",
                budget=120000,
                spend=87000,
                revenue=78000,
                roas=0.9,
                influencers=10,
                progress=55,
                start_date="2026-08-01",
                end_date="2026-09-30",
                conversions=64,
                reach=890000,
                objective="UGC",
                description="User generated authentic reviews and morning routine reels.",
            ),
            Campaign(
                id="camp-5",
                owner_id=demo_user.id,
                name="Men's Skincare Pilot",
                brand="GlowNaturals",
                status="planning",
                health="healthy",
                budget=80000,
                spend=0,
                revenue=0,
                roas=0,
                influencers=0,
                progress=10,
                start_date="2026-10-01",
                end_date="2026-11-15",
                conversions=0,
                reach=0,
                objective="Product Launch",
                description="Targeted men's grooming and simplified routine line.",
            ),
        ]
        db.add_all(campaigns_data)

        # 3. Influencers
        influencers_data = [
            Influencer(
                id="inf-1",
                name="Rhea Kapoor",
                username="@rhea_glows",
                avatar="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
                platform="instagram",
                verified=True,
                niches=["Skincare", "Clean Beauty", "Dermatology"],
                followers=84200,
                engagement_rate=5.8,
                avg_views=42000,
                avg_likes=4900,
                avg_comments=320,
                estimated_cost=18000,
                location="Mumbai, India",
                ai_match_score=94,
                predicted_roas=3.4,
                audience_fit=92,
                authenticity=96,
                brand_safety=98,
                niche_match=95,
                budget_fit=90,
                audience_gender={"female": 82, "male": 16, "other": 2},
                audience_age=[
                    {"range": "18-24", "percent": 34},
                    {"range": "25-34", "percent": 48},
                    {"range": "35-44", "percent": 14},
                    {"range": "45+", "percent": 4},
                ],
                top_countries=[
                    {"country": "India", "percent": 84},
                    {"country": "UAE", "percent": 8},
                    {"country": "US", "percent": 5},
                    {"country": "UK", "percent": 3},
                ],
                top_cities=["Mumbai", "Delhi", "Bangalore", "Pune"],
                interests=["Skincare Routine", "Clean Ingredients", "Aesthetics", "Wellness"],
                why_recommended="High engagement within 25–34 clean beauty demographic; excellent past product conversion.",
                shortlisted=True,
                status="accepted",
            ),
            Influencer(
                id="inf-2",
                name="Aanya Verma",
                username="@aanyaskindiary",
                avatar="https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop&crop=face",
                platform="instagram",
                verified=True,
                niches=["Clean Beauty", "Organic Lifestyle", "Skincare"],
                followers=128000,
                engagement_rate=4.9,
                avg_views=68000,
                avg_likes=6200,
                avg_comments=410,
                estimated_cost=25000,
                location="Delhi, India",
                ai_match_score=91,
                predicted_roas=3.1,
                audience_fit=89,
                authenticity=94,
                brand_safety=97,
                niche_match=92,
                budget_fit=86,
                audience_gender={"female": 78, "male": 20, "other": 2},
                audience_age=[
                    {"range": "18-24", "percent": 28},
                    {"range": "25-34", "percent": 54},
                    {"range": "35-44", "percent": 14},
                    {"range": "45+", "percent": 4},
                ],
                top_countries=[
                    {"country": "India", "percent": 88},
                    {"country": "Singapore", "percent": 6},
                    {"country": "UAE", "percent": 4},
                    {"country": "UK", "percent": 2},
                ],
                top_cities=["Delhi", "Gurugram", "Noida", "Chandigarh"],
                interests=["Organic Living", "Ayurvedic Skincare", "Sustainable Lifestyle"],
                why_recommended="Consistent high-view reels on skincare routines with high save rate.",
                shortlisted=True,
                status="negotiating",
            ),
            Influencer(
                id="inf-3",
                name="Dr. Kabir Sen",
                username="@drkabir_derm",
                avatar="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
                platform="youtube",
                verified=True,
                niches=["Dermatology", "Ingredient Science", "Skincare"],
                followers=245000,
                engagement_rate=6.2,
                avg_views=140000,
                avg_likes=8700,
                avg_comments=890,
                estimated_cost=45000,
                location="Bangalore, India",
                ai_match_score=96,
                predicted_roas=3.8,
                audience_fit=95,
                authenticity=99,
                brand_safety=99,
                niche_match=98,
                budget_fit=82,
                audience_gender={"female": 68, "male": 30, "other": 2},
                audience_age=[
                    {"range": "18-24", "percent": 22},
                    {"range": "25-34", "percent": 58},
                    {"range": "35-44", "percent": 16},
                    {"range": "45+", "percent": 4},
                ],
                top_countries=[
                    {"country": "India", "percent": 80},
                    {"country": "US", "percent": 10},
                    {"country": "UK", "percent": 6},
                    {"country": "Canada", "percent": 4},
                ],
                top_cities=["Bangalore", "Hyderabad", "Chennai", "Mumbai"],
                interests=["Derm Reviews", "Ingredient Analysis", "Acne Solutions"],
                why_recommended="Highest authority rating in ingredient science; boosts brand credibility and ROAS.",
                shortlisted=True,
                status="sent",
            ),
        ]
        db.add_all(influencers_data)

        # 4. Approvals
        approvals_data = [
            Approval(
                id="appr-1",
                agent="Negotiation Agent",
                type="negotiation",
                action="Accept revised fee of ₹18,000 for Rhea Kapoor (was ₹22,000)",
                reason="18% discount secured for 2 Reels + 3 Stories bundle. Projected ROAS remains strong at 3.4x.",
                campaign="GlowNaturals Summer Launch",
                financial_impact="Save ₹4,000 against budget",
                confidence=94,
                timestamp="10 min ago",
                status="pending",
            ),
            Approval(
                id="appr-2",
                agent="Strategy Agent",
                type="budget",
                action="Reallocate ₹25,000 from UGC Drive to Summer Launch",
                reason="Summer Launch ROAS (3.06x) is outperforming UGC Drive (0.90x). Moving budget will capture higher conversion momentum.",
                campaign="Multi-campaign reallocation",
                financial_impact="+₹51,000 projected revenue",
                confidence=91,
                timestamp="32 min ago",
                status="pending",
            ),
            Approval(
                id="appr-3",
                agent="Outreach Agent",
                type="outreach",
                action="Send batch outreach to 12 shortlisted micro-creators",
                reason="Personalized message drafts generated and verified against brand voice safety guidelines.",
                campaign="Vitamin C Serum Awareness",
                financial_impact="Est. spend ₹1.2L across 12 creators",
                confidence=89,
                timestamp="1 hour ago",
                status="pending",
            ),
            Approval(
                id="appr-4",
                agent="Contract Agent",
                type="contract",
                action="Flag and request amendment: Dr. Kabir Sen exclusivity clause",
                reason="Draft contract lacks category exclusivity for 60 days. Risk of competitor promotion during campaign window.",
                campaign="Summer Launch",
                financial_impact="Brand protection / zero fee change",
                confidence=96,
                timestamp="2 hours ago",
                status="pending",
            ),
        ]
        db.add_all(approvals_data)

        # 5. Contracts
        contracts_data = [
            Contract(
                id="ct-101",
                creator="Rhea Kapoor",
                username="@rhea_glows",
                campaign="GlowNaturals Summer Launch",
                value=18000,
                status="signed",
                start_date="2026-08-20",
                end_date="2026-09-20",
                payment_due="2026-09-25",
                risk="low",
                deliverables=["1x Dedicated Reel", "2x Story with link", "1x Static post"],
                usage_rights="6 months digital paid ads",
                exclusivity="30 days skincare category",
                ai_risks=["No competitor mentions 14 days prior verified"],
            ),
            Contract(
                id="ct-102",
                creator="Aanya Verma",
                username="@aanyaskindiary",
                campaign="GlowNaturals Summer Launch",
                value=25000,
                status="pending_signature",
                start_date="2026-08-25",
                end_date="2026-09-25",
                payment_due="2026-09-30",
                risk="medium",
                deliverables=["2x Dedicated Reels", "3x Story series"],
                usage_rights="3 months organic reposting",
                exclusivity="None requested",
                ai_risks=["Exclusivity clause recommended for cleaner campaign attribution"],
            ),
            Contract(
                id="ct-103",
                creator="Dr. Kabir Sen",
                username="@drkabir_derm",
                campaign="GlowNaturals Summer Launch",
                value=45000,
                status="at_risk",
                start_date="2026-09-01",
                end_date="2026-10-01",
                payment_due="2026-10-05",
                risk="high",
                deliverables=["1x YouTube Integration (8-10 min)", "1x Short"],
                usage_rights="12 months digital rights",
                exclusivity="60 days dermatology & clean beauty",
                ai_risks=["Clause 4.2 missing standard liability limit", "Payment terms specify 100% upfront (standard is 50/50)"],
            ),
        ]
        db.add_all(contracts_data)

        # 6. Agents
        agents_data = [
            Agent(
                id="agent-supervisor",
                name="Supervisor Agent",
                role="Campaign Orchestrator & Coordinator",
                status="active",
                current_task="Coordinating multi-agent workflow for Summer Launch",
                last_action="Delegated outreach approval check to human supervisor",
                tasks_completed=142,
                avg_execution_time="1.2s",
                success_rate=98.4,
                last_active="Active now",
                progress=75,
                started_at="Today, 09:00 AM",
            ),
            Agent(
                id="agent-strategy",
                name="Strategy Agent",
                role="Budget Allocation & Creator Mix Strategy",
                status="active",
                current_task="Simulating ROAS impact of ₹25k budget shift",
                last_action="Generated recommendation #REC-204 for Summer Launch",
                tasks_completed=89,
                avg_execution_time="3.4s",
                success_rate=96.1,
                last_active="2 min ago",
                progress=90,
                started_at="Today, 09:15 AM",
            ),
            Agent(
                id="agent-discovery",
                name="Discovery Agent",
                role="Influencer Search & Audience Fit Scoring",
                status="processing",
                current_task="Scanning 487 Instagram creator profiles in India",
                last_action="Scored Rhea Kapoor: 94 match score, 3.4 predicted ROAS",
                tasks_completed=312,
                avg_execution_time="0.8s",
                success_rate=99.1,
                last_active="Active now",
                progress=68,
                started_at="Today, 09:30 AM",
            ),
            Agent(
                id="agent-outreach",
                name="Outreach Agent",
                role="Personalized DM & Email Communication",
                status="idle",
                current_task="Awaiting human approval for 12 outreach drafts",
                last_action="Prepared 12 customized pitches with personalized handles",
                tasks_completed=98,
                avg_execution_time="2.1s",
                success_rate=94.2,
                last_active="15 min ago",
                progress=100,
                started_at="Today, 08:45 AM",
            ),
            Agent(
                id="agent-contract",
                name="Contract Agent",
                role="Contract Generation & AI Risk Review",
                status="idle",
                current_task="Monitoring pending signatures on DocuSign",
                last_action="Flagged 2 risk clauses in Dr. Kabir Sen contract",
                tasks_completed=44,
                avg_execution_time="4.6s",
                success_rate=97.8,
                last_active="45 min ago",
                progress=100,
                started_at="Today, 08:00 AM",
            ),
            Agent(
                id="agent-performance",
                name="Performance Agent",
                role="Real-time Tracking & ROI Optimization",
                status="active",
                current_task="Tracking reel views and conversion pixels",
                last_action="Updated live ROAS to 3.06x on Summer Launch",
                tasks_completed=512,
                avg_execution_time="0.4s",
                success_rate=99.7,
                last_active="Active now",
                progress=82,
                started_at="Today, 07:00 AM",
            ),
        ]
        db.add_all(agents_data)

        # 7. Outreach Messages
        outreach_data = [
            OutreachMessage(
                id="msg-1",
                influencer_id="inf-1",
                influencer_name="Rhea Kapoor",
                influencer_username="@rhea_glows",
                campaign_name="GlowNaturals Summer Launch",
                channel="Instagram DM",
                subject="Collaboration with GlowNaturals — Summer Hydration Campaign",
                body="Hi Rhea! Loved your recent breakdown on clean SPF routines. We are launching GlowNaturals HydraGlow Gel and think your skin philosophy aligns seamlessly with our clean formula. We'd love to partner for a 2-reel collaboration. Let us know if you're open to exploring!",
                status="accepted",
                sent_at="2026-08-12 10:30 AM",
                reply="Hey team! Would love to test the product first. Send over details!",
            ),
            OutreachMessage(
                id="msg-2",
                influencer_id="inf-2",
                influencer_name="Aanya Verma",
                influencer_username="@aanyaskindiary",
                campaign_name="GlowNaturals Summer Launch",
                channel="Instagram DM",
                subject="GlowNaturals Launch Partnership",
                body="Hey Aanya! Your honest reviews on organic skincare are fantastic. We'd love to collaborate on our upcoming GlowNaturals Summer Launch campaign. We have an exclusive gifting kit & sponsored reel opportunity.",
                status="negotiating",
                sent_at="2026-08-14 02:15 PM",
                reply="Interested! What is the deliverable timeline?",
            ),
        ]
        db.add_all(outreach_data)

        # 8. Timeline Events
        timeline_data = [
            TimelineEvent(
                id="tl-1",
                time="10 min ago",
                agent="Negotiation Agent",
                message="Secured 18% fee reduction with Rhea Kapoor (@rhea_glows). Awaiting your approval.",
                type="action",
            ),
            TimelineEvent(
                id="tl-2",
                time="32 min ago",
                agent="Strategy Agent",
                message="Detected ROAS divergence: Summer Launch (3.06x) vs UGC (0.90x). Recommended budget shift.",
                type="info",
            ),
            TimelineEvent(
                id="tl-3",
                time="1 hour ago",
                agent="Discovery Agent",
                message="Scanned 487 creators. 68 high-fit candidates matched for clean beauty tier.",
                type="success",
            ),
            TimelineEvent(
                id="tl-4",
                time="2 hours ago",
                agent="Contract Agent",
                message="Flagged missing category exclusivity in Dr. Kabir Sen contract draft.",
                type="action",
            ),
        ]
        db.add_all(timeline_data)

        await db.commit()
        print("Database seeding completed successfully.")
