"""create initial schema

Revision ID: 19bd12886dea
Revises: 
Create Date: 2026-08-11 17:05:54.808220

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db.custom_types


# revision identifiers, used by Alembic.
revision: str = '19bd12886dea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_task', sa.String(length=500), nullable=False),
    sa.Column('last_action', sa.String(length=500), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('avg_execution_time', sa.String(length=50), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('last_active', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('campaign', sa.String(length=255), nullable=False),
    sa.Column('financial_impact', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('creator', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('campaign', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=False),
    sa.Column('payment_due', sa.String(length=50), nullable=False),
    sa.Column('risk', sa.String(length=50), nullable=False),
    sa.Column('deliverables', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('usage_rights', sa.String(length=255), nullable=False),
    sa.Column('exclusivity', sa.String(length=255), nullable=False),
    sa.Column('ai_risks', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('influencers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('niches', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('avg_views', sa.Integer(), nullable=False),
    sa.Column('avg_likes', sa.Integer(), nullable=False),
    sa.Column('avg_comments', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('ai_match_score', sa.Float(), nullable=False),
    sa.Column('predicted_roas', sa.Float(), nullable=False),
    sa.Column('audience_fit', sa.Float(), nullable=False),
    sa.Column('authenticity', sa.Float(), nullable=False),
    sa.Column('brand_safety', sa.Float(), nullable=False),
    sa.Column('niche_match', sa.Float(), nullable=False),
    sa.Column('budget_fit', sa.Float(), nullable=False),
    sa.Column('audience_gender', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('audience_age', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('top_countries', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('top_cities', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('interests', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('why_recommended', sa.Text(), nullable=False),
    sa.Column('shortlisted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_id'), 'influencers', ['id'], unique=False)
    op.create_index(op.f('ix_influencers_username'), 'influencers', ['username'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_table('metric_cards',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('context', sa.String(length=255), nullable=False),
    sa.Column('trend_value', sa.String(length=50), nullable=True),
    sa.Column('trend_positive', sa.Boolean(), nullable=True),
    sa.Column('sparkline', app.db.custom_types.JSON_COMPAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_cards_id'), 'metric_cards', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=50), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('optimization_recs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('current_data', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('moves', app.db.custom_types.JSON_COMPAT(), nullable=False),
    sa.Column('expected_revenue', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_recs_id'), 'optimization_recs', ['id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('influencer_id', sa.String(length=64), nullable=False),
    sa.Column('influencer_name', sa.String(length=255), nullable=False),
    sa.Column('influencer_username', sa.String(length=255), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.String(length=50), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_messages_id'), 'outreach_messages', ['id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_influencer_id'), 'outreach_messages', ['influencer_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_id'), 'timeline_events', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health', sa.String(length=50), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('roas', sa.Float(), nullable=False),
    sa.Column('influencers', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=False),
    sa.Column('end_date', sa.String(length=50), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_types', app.db.custom_types.JSON_COMPAT(), nullable=True),
    sa.Column('target_locations', sa.String(length=255), nullable=True),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('target_gender', sa.String(length=50), nullable=True),
    sa.Column('interests', app.db.custom_types.JSON_COMPAT(), nullable=True),
    sa.Column('languages', app.db.custom_types.JSON_COMPAT(), nullable=True),
    sa.Column('platforms', app.db.custom_types.JSON_COMPAT(), nullable=True),
    sa.Column('creator_tiers', app.db.custom_types.JSON_COMPAT(), nullable=True),
    sa.Column('budget_allocation', app.db.custom_types.JSON_COMPAT(), nullable=True),
    sa.Column('primary_kpi', sa.String(length=100), nullable=True),
    sa.Column('target_roas', sa.Float(), nullable=True),
    sa.Column('target_cpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_owner_id'), 'campaigns', ['owner_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('user_id', app.db.custom_types.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_id'), 'refresh_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_campaigns_owner_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_timeline_events_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_outreach_messages_influencer_id'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_optimization_recs_id'), table_name='optimization_recs')
    op.drop_table('optimization_recs')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_metric_cards_id'), table_name='metric_cards')
    op.drop_table('metric_cards')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_influencers_username'), table_name='influencers')
    op.drop_index(op.f('ix_influencers_id'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
