import type {
  Agent,
  ApprovalItem,
  Campaign,
  Contract,
  FunnelStage,
  Influencer,
  Insight,
  MetricCard,
  NotificationItem,
  OptimizationRec,
  TimelineEvent,
} from '@/types'

export const workspace = {
  name: 'GlowNaturals Marketing',
  user: 'Aaditya Sharma',
  role: 'Marketing Manager',
  email: 'aaditya@glownaturals.com',
}

export const dashboardMetrics: MetricCard[] = [
  {
    id: 'active',
    label: 'Active Campaigns',
    value: '8',
    context: '+2 this month',
    trend: { value: '+2', positive: true },
    sparkline: [3, 4, 4, 5, 6, 7, 8],
  },
  {
    id: 'spend',
    label: 'Total Spend',
    value: '₹6.4L',
    context: '72% of allocated budget',
    sparkline: [2.1, 2.8, 3.4, 4.2, 5.1, 5.8, 6.4],
  },
  {
    id: 'revenue',
    label: 'Revenue Generated',
    value: '₹18.2L',
    context: '+23.8% vs last period',
    trend: { value: '+23.8%', positive: true },
    sparkline: [8, 10, 11, 13, 15, 16.5, 18.2],
  },
  {
    id: 'roas',
    label: 'Average ROAS',
    value: '2.84x',
    context: '+0.31x improvement',
    trend: { value: '+0.31x', positive: true },
    sparkline: [2.1, 2.2, 2.4, 2.5, 2.6, 2.7, 2.84],
  },
  {
    id: 'influencers',
    label: 'Influencers Active',
    value: '46',
    context: 'Across 8 campaigns',
    sparkline: [18, 22, 28, 32, 38, 42, 46],
  },
  {
    id: 'approvals',
    label: 'Pending Approvals',
    value: '5',
    context: '3 high priority',
    trend: { value: 'Needs review', positive: false },
  },
]

export const campaigns: Campaign[] = [
  {
    id: 'camp-1',
    name: 'GlowNaturals Summer Launch',
    brand: 'GlowNaturals',
    status: 'active',
    health: 'excellent',
    budget: 200000,
    spend: 128000,
    revenue: 392000,
    roas: 3.06,
    influencers: 8,
    progress: 64,
    startDate: '2026-08-20',
    endDate: '2026-09-20',
    conversions: 426,
    reach: 1800000,
    objective: 'Product Launch',
  },
  {
    id: 'camp-2',
    name: 'Vitamin C Serum Awareness',
    brand: 'GlowNaturals',
    status: 'active',
    health: 'healthy',
    budget: 150000,
    spend: 98000,
    revenue: 245000,
    roas: 2.5,
    influencers: 6,
    progress: 72,
    startDate: '2026-07-15',
    endDate: '2026-09-15',
    conversions: 312,
    reach: 1200000,
    objective: 'Awareness',
  },
  {
    id: 'camp-3',
    name: 'Festive Glow Collection',
    brand: 'GlowNaturals',
    status: 'active',
    health: 'healthy',
    budget: 180000,
    spend: 45000,
    revenue: 89000,
    roas: 1.98,
    influencers: 5,
    progress: 28,
    startDate: '2026-09-01',
    endDate: '2026-10-15',
    conversions: 98,
    reach: 420000,
    objective: 'Conversions',
  },
  {
    id: 'camp-4',
    name: 'Clean Beauty UGC Drive',
    brand: 'GlowNaturals',
    status: 'active',
    health: 'needs_attention',
    budget: 120000,
    spend: 87000,
    revenue: 78000,
    roas: 0.9,
    influencers: 10,
    progress: 55,
    startDate: '2026-08-01',
    endDate: '2026-09-30',
    conversions: 64,
    reach: 890000,
    objective: 'UGC',
  },
  {
    id: 'camp-5',
    name: 'Men\'s Skincare Pilot',
    brand: 'GlowNaturals',
    status: 'planning',
    health: 'healthy',
    budget: 80000,
    spend: 0,
    revenue: 0,
    roas: 0,
    influencers: 0,
    progress: 12,
    startDate: '2026-09-15',
    endDate: '2026-10-15',
    conversions: 0,
    reach: 0,
    objective: 'Awareness',
  },
]

export const revenueSpendData = [
  { date: 'Aug 1', revenue: 18000, spend: 12000 },
  { date: 'Aug 5', revenue: 32000, spend: 18000 },
  { date: 'Aug 10', revenue: 48000, spend: 28000 },
  { date: 'Aug 15', revenue: 72000, spend: 42000 },
  { date: 'Aug 20', revenue: 98000, spend: 58000 },
  { date: 'Aug 25', revenue: 145000, spend: 78000 },
  { date: 'Aug 30', revenue: 198000, spend: 95000 },
  { date: 'Sep 5', revenue: 268000, spend: 112000 },
  { date: 'Sep 10', revenue: 342000, spend: 122000 },
  { date: 'Sep 15', revenue: 392000, spend: 128000 },
]

export const campaignHealth = {
  excellent: 2,
  healthy: 5,
  needsAttention: 1,
}

export const aiInsights: Insight[] = [
  {
    id: 'ins-1',
    title: 'Top performer detected',
    body: 'NehaBeauty is currently generating 42% higher conversion efficiency than the campaign average.',
    impact: '+₹42K projected',
    confidence: 94,
    action: 'Increase allocation',
    type: 'opportunity',
  },
  {
    id: 'ins-2',
    title: 'Budget reallocation opportunity',
    body: '₹18,000 of budget could potentially be reallocated from underperforming creators.',
    impact: '+₹31–38K revenue',
    confidence: 86,
    action: 'Review recommendation',
    type: 'warning',
  },
  {
    id: 'ins-3',
    title: 'Content format insight',
    body: 'Instagram Reels account for 71% of campaign-generated revenue across active campaigns.',
    impact: 'Format priority',
    confidence: 91,
    action: 'View details',
    type: 'info',
  },
]

export const agents: Agent[] = [
  {
    id: 'supervisor',
    name: 'Supervisor Agent',
    role: 'Coordinates everything',
    status: 'active',
    currentTask: 'Orchestrating Summer Launch workflow',
    lastAction: 'Assigned Discovery Agent to creator analysis',
    tasksCompleted: 1248,
    avgExecutionTime: '1.2s',
    successRate: 99.2,
    lastActive: 'Just now',
    progress: 78,
    startedAt: '10:30 AM',
  },
  {
    id: 'strategy',
    name: 'Strategy Agent',
    role: 'Plans campaign direction',
    status: 'completed',
    currentTask: 'Strategy ready for review',
    lastAction: 'Generated recommended creator mix',
    tasksCompleted: 342,
    avgExecutionTime: '8.4s',
    successRate: 97.8,
    lastActive: '4 min ago',
    progress: 100,
    startedAt: '10:32 AM',
  },
  {
    id: 'discovery',
    name: 'Discovery Agent',
    role: 'Finds the best-fit creators',
    status: 'active',
    currentTask: 'Analyzing creators for GlowNaturals',
    lastAction: 'Shortlisted 14 creators from 487 analyzed',
    tasksCompleted: 487,
    avgExecutionTime: '3.1s',
    successRate: 96.4,
    lastActive: '12 seconds ago',
    progress: 72,
    startedAt: '10:34 AM',
  },
  {
    id: 'outreach',
    name: 'Outreach Agent',
    role: 'Personalizes conversations',
    status: 'processing',
    currentTask: 'Preparing personalized messages',
    lastAction: 'Drafted 6 outreach messages',
    tasksCompleted: 218,
    avgExecutionTime: '2.6s',
    successRate: 98.1,
    lastActive: '45 seconds ago',
    progress: 55,
    startedAt: '10:37 AM',
  },
  {
    id: 'contract',
    name: 'Contract Agent',
    role: 'Tracks obligations and risks',
    status: 'idle',
    currentTask: 'Waiting for signed contracts',
    lastAction: 'Flagged exclusivity risk on 1 contract',
    tasksCompleted: 156,
    avgExecutionTime: '4.2s',
    successRate: 99.0,
    lastActive: '18 min ago',
  },
  {
    id: 'performance',
    name: 'Performance Agent',
    role: 'Analyzes campaign health',
    status: 'active',
    currentTask: 'Monitoring live campaign metrics',
    lastAction: 'Updated ROAS forecasts',
    tasksCompleted: 892,
    avgExecutionTime: '1.8s',
    successRate: 98.7,
    lastActive: '8 seconds ago',
    progress: 40,
    startedAt: '09:15 AM',
  },
  {
    id: 'optimization',
    name: 'Optimization Agent',
    role: 'Finds opportunities to improve ROI',
    status: 'processing',
    currentTask: 'Evaluating budget reallocation',
    lastAction: 'Proposed ₹10K reallocation',
    tasksCompleted: 204,
    avgExecutionTime: '5.5s',
    successRate: 94.2,
    lastActive: '2 min ago',
    progress: 88,
    startedAt: '10:28 AM',
  },
]

export const agentTimeline: TimelineEvent[] = [
  { id: 't1', time: '10:32', agent: 'Strategy Agent', message: 'Started campaign analysis.', type: 'info' },
  { id: 't2', time: '10:33', agent: 'Strategy Agent', message: 'Generated recommended creator mix.', type: 'success' },
  { id: 't3', time: '10:34', agent: 'Supervisor Agent', message: 'Assigned Discovery Agent.', type: 'action' },
  { id: 't4', time: '10:34', agent: 'Discovery Agent', message: 'Analyzed 487 influencers.', type: 'info' },
  { id: 't5', time: '10:35', agent: 'Discovery Agent', message: 'Shortlisted 14 creators.', type: 'success' },
  { id: 't6', time: '10:36', agent: 'Human', message: 'Approved 6 creators.', type: 'human' },
  { id: 't7', time: '10:37', agent: 'Outreach Agent', message: 'Prepared personalized messages.', type: 'action' },
  { id: 't8', time: '10:39', agent: 'Optimization Agent', message: 'Detected underperforming creator allocation.', type: 'info' },
]

export const influencers: Influencer[] = [
  {
    id: 'inf-1',
    name: 'Aditi Sharma',
    username: 'aditibeauty',
    avatar: 'AS',
    platform: 'instagram',
    verified: true,
    niches: ['Beauty', 'Skincare'],
    followers: 184000,
    engagementRate: 6.2,
    avgViews: 92000,
    avgLikes: 11400,
    avgComments: 420,
    estimatedCost: 22000,
    location: 'Mumbai, India',
    aiMatchScore: 94,
    predictedRoas: 3.4,
    audienceFit: 91,
    authenticity: 88,
    brandSafety: 96,
    nicheMatch: 95,
    budgetFit: 90,
    audienceGender: { male: 18, female: 79, other: 3 },
    audienceAge: [
      { range: '18-24', percent: 32 },
      { range: '25-34', percent: 48 },
      { range: '35-44', percent: 15 },
      { range: '45+', percent: 5 },
    ],
    topCountries: [
      { country: 'India', percent: 78 },
      { country: 'UAE', percent: 8 },
      { country: 'USA', percent: 6 },
    ],
    topCities: ['Mumbai', 'Delhi', 'Bangalore', 'Pune'],
    interests: ['Skincare', 'Clean beauty', 'Wellness', 'Lifestyle'],
    whyRecommended:
      "81% of Aditi's audience matches your target demographic. Her skincare content consistently generates above-average engagement and her estimated rate falls within your campaign's preferred CPA range.",
    shortlisted: true,
    status: 'awaiting_approval',
  },
  {
    id: 'inf-2',
    name: 'Neha Kapoor',
    username: 'NehaBeauty',
    avatar: 'NK',
    platform: 'instagram',
    verified: true,
    niches: ['Beauty', 'Lifestyle'],
    followers: 312000,
    engagementRate: 5.8,
    avgViews: 145000,
    avgLikes: 18200,
    avgComments: 680,
    estimatedCost: 18000,
    location: 'Delhi, India',
    aiMatchScore: 97,
    predictedRoas: 4.1,
    audienceFit: 94,
    authenticity: 92,
    brandSafety: 98,
    nicheMatch: 96,
    budgetFit: 95,
    audienceGender: { male: 12, female: 85, other: 3 },
    audienceAge: [
      { range: '18-24', percent: 28 },
      { range: '25-34', percent: 52 },
      { range: '35-44', percent: 14 },
      { range: '45+', percent: 6 },
    ],
    topCountries: [
      { country: 'India', percent: 82 },
      { country: 'UK', percent: 7 },
      { country: 'USA', percent: 5 },
    ],
    topCities: ['Delhi', 'Gurgaon', 'Noida', 'Chandigarh'],
    interests: ['Skincare routines', 'Product reviews', 'Makeup'],
    whyRecommended:
      'Top conversion efficiency in similar beauty campaigns. Strong overlap with GlowNaturals buyer personas and proven ROAS of 4.1x on current spend.',
    shortlisted: true,
    status: 'accepted',
  },
  {
    id: 'inf-3',
    name: 'Riya Mehta',
    username: 'RiyaStyle',
    avatar: 'RM',
    platform: 'instagram',
    verified: false,
    niches: ['Fashion', 'Lifestyle'],
    followers: 256000,
    engagementRate: 3.1,
    avgViews: 68000,
    avgLikes: 7900,
    avgComments: 210,
    estimatedCost: 31000,
    location: 'Bangalore, India',
    aiMatchScore: 62,
    predictedRoas: 0.9,
    audienceFit: 58,
    authenticity: 71,
    brandSafety: 88,
    nicheMatch: 55,
    budgetFit: 48,
    audienceGender: { male: 35, female: 62, other: 3 },
    audienceAge: [
      { range: '18-24', percent: 45 },
      { range: '25-34', percent: 35 },
      { range: '35-44', percent: 14 },
      { range: '45+', percent: 6 },
    ],
    topCountries: [
      { country: 'India', percent: 70 },
      { country: 'USA', percent: 12 },
      { country: 'Canada', percent: 6 },
    ],
    topCities: ['Bangalore', 'Hyderabad', 'Chennai'],
    interests: ['Fashion', 'Street style', 'Travel'],
    whyRecommended:
      'Initially shortlisted for reach, but conversion rate is 47% below campaign average. Optimization Agent recommends reducing allocation.',
    shortlisted: true,
    status: 'negotiating',
  },
  {
    id: 'inf-4',
    name: 'Kabir Jain',
    username: 'kabirwellness',
    avatar: 'KJ',
    platform: 'youtube',
    verified: true,
    niches: ['Fitness', 'Wellness'],
    followers: 420000,
    engagementRate: 4.9,
    avgViews: 210000,
    avgLikes: 9800,
    avgComments: 540,
    estimatedCost: 45000,
    location: 'Pune, India',
    aiMatchScore: 78,
    predictedRoas: 2.6,
    audienceFit: 72,
    authenticity: 90,
    brandSafety: 95,
    nicheMatch: 68,
    budgetFit: 70,
    audienceGender: { male: 58, female: 40, other: 2 },
    audienceAge: [
      { range: '18-24', percent: 30 },
      { range: '25-34', percent: 44 },
      { range: '35-44', percent: 20 },
      { range: '45+', percent: 6 },
    ],
    topCountries: [
      { country: 'India', percent: 75 },
      { country: 'USA', percent: 10 },
      { country: 'Australia', percent: 5 },
    ],
    topCities: ['Pune', 'Mumbai', 'Ahmedabad'],
    interests: ['Fitness', 'Nutrition', 'Mens grooming'],
    whyRecommended:
      'Strong YouTube performance for longer-form product education. Good fit for serum routine explainers.',
    status: 'draft_ready',
  },
  {
    id: 'inf-5',
    name: 'Sara Ali',
    username: 'saraglows',
    avatar: 'SA',
    platform: 'tiktok',
    verified: true,
    niches: ['Beauty', 'Education'],
    followers: 890000,
    engagementRate: 7.4,
    avgViews: 520000,
    avgLikes: 42000,
    avgComments: 1200,
    estimatedCost: 38000,
    location: 'Hyderabad, India',
    aiMatchScore: 89,
    predictedRoas: 3.1,
    audienceFit: 86,
    authenticity: 84,
    brandSafety: 92,
    nicheMatch: 90,
    budgetFit: 75,
    audienceGender: { male: 22, female: 75, other: 3 },
    audienceAge: [
      { range: '18-24', percent: 48 },
      { range: '25-34', percent: 38 },
      { range: '35-44', percent: 10 },
      { range: '45+', percent: 4 },
    ],
    topCountries: [
      { country: 'India', percent: 65 },
      { country: 'USA', percent: 15 },
      { country: 'UK', percent: 8 },
    ],
    topCities: ['Hyderabad', 'Mumbai', 'Delhi'],
    interests: ['Skincare tips', 'Dermatology', 'Product demos'],
    whyRecommended:
      'Exceptional TikTok reach with educational skincare hooks that align with GlowNaturals brand voice.',
    shortlisted: true,
    status: 'sent',
  },
  {
    id: 'inf-6',
    name: 'Maya Chen',
    username: 'mayaskincare',
    avatar: 'MC',
    platform: 'instagram',
    verified: false,
    niches: ['Beauty', 'Travel'],
    followers: 98000,
    engagementRate: 8.1,
    avgViews: 45000,
    avgLikes: 7900,
    avgComments: 310,
    estimatedCost: 12000,
    location: 'Goa, India',
    aiMatchScore: 91,
    predictedRoas: 3.8,
    audienceFit: 88,
    authenticity: 93,
    brandSafety: 97,
    nicheMatch: 92,
    budgetFit: 98,
    audienceGender: { male: 15, female: 82, other: 3 },
    audienceAge: [
      { range: '18-24', percent: 25 },
      { range: '25-34', percent: 55 },
      { range: '35-44', percent: 15 },
      { range: '45+', percent: 5 },
    ],
    topCountries: [
      { country: 'India', percent: 72 },
      { country: 'Singapore', percent: 10 },
      { country: 'UAE', percent: 7 },
    ],
    topCities: ['Goa', 'Mumbai', 'Bangalore'],
    interests: ['Clean beauty', 'Travel routines', 'Natural products'],
    whyRecommended:
      'Micro creator with elite engagement. Excellent CPA efficiency and high authenticity score.',
    shortlisted: true,
    status: 'not_contacted',
  },
  {
    id: 'inf-7',
    name: 'Arjun Patel',
    username: 'arjuntechlife',
    avatar: 'AP',
    platform: 'youtube',
    verified: true,
    niches: ['Technology', 'Lifestyle'],
    followers: 610000,
    engagementRate: 3.8,
    avgViews: 280000,
    avgLikes: 12000,
    avgComments: 890,
    estimatedCost: 55000,
    location: 'Ahmedabad, India',
    aiMatchScore: 54,
    predictedRoas: 1.4,
    audienceFit: 42,
    authenticity: 86,
    brandSafety: 94,
    nicheMatch: 38,
    budgetFit: 45,
    audienceGender: { male: 72, female: 26, other: 2 },
    audienceAge: [
      { range: '18-24', percent: 40 },
      { range: '25-34', percent: 42 },
      { range: '35-44', percent: 14 },
      { range: '45+', percent: 4 },
    ],
    topCountries: [
      { country: 'India', percent: 80 },
      { country: 'USA', percent: 8 },
      { country: 'Canada', percent: 4 },
    ],
    topCities: ['Ahmedabad', 'Surat', 'Mumbai'],
    interests: ['Gadgets', 'Reviews', 'Productivity'],
    whyRecommended:
      'Lower niche match for beauty. Discovery Agent ranked this creator outside preferred threshold.',
    status: 'not_contacted',
  },
  {
    id: 'inf-8',
    name: 'Priya Nair',
    username: 'priyaeats',
    avatar: 'PN',
    platform: 'instagram',
    verified: true,
    niches: ['Food', 'Lifestyle'],
    followers: 145000,
    engagementRate: 5.2,
    avgViews: 72000,
    avgLikes: 7500,
    avgComments: 280,
    estimatedCost: 16000,
    location: 'Kochi, India',
    aiMatchScore: 71,
    predictedRoas: 2.2,
    audienceFit: 68,
    authenticity: 89,
    brandSafety: 95,
    nicheMatch: 60,
    budgetFit: 85,
    audienceGender: { male: 28, female: 70, other: 2 },
    audienceAge: [
      { range: '18-24', percent: 22 },
      { range: '25-34', percent: 48 },
      { range: '35-44', percent: 22 },
      { range: '45+', percent: 8 },
    ],
    topCountries: [
      { country: 'India', percent: 85 },
      { country: 'UAE', percent: 6 },
      { country: 'USA', percent: 4 },
    ],
    topCities: ['Kochi', 'Bangalore', 'Chennai'],
    interests: ['Food', 'Wellness', 'Home lifestyle'],
    whyRecommended:
      'Adjacent lifestyle fit for wellness-adjacent product moments. Moderate predicted ROAS.',
    status: 'replied',
  },
]

export const campaignFunnel: FunnelStage[] = [
  { label: 'Discovered', value: 120 },
  { label: 'Recommended', value: 24 },
  { label: 'Shortlisted', value: 12 },
  { label: 'Contacted', value: 8 },
  { label: 'Accepted', value: 6 },
  { label: 'Live', value: 5 },
  { label: 'Completed', value: 2 },
]

export const creatorPerformance = [
  { influencer: 'NehaBeauty', spend: 18000, reach: 420000, clicks: 12400, conversions: 186, revenue: 73800, roas: 4.1, cpa: 97, performance: 'excellent' as const },
  { influencer: 'AditiBeauty', spend: 22000, reach: 310000, clicks: 9800, conversions: 142, revenue: 61200, roas: 2.78, cpa: 155, performance: 'healthy' as const },
  { influencer: 'SaraGlows', spend: 38000, reach: 680000, clicks: 15200, conversions: 168, revenue: 92400, roas: 2.43, cpa: 226, performance: 'healthy' as const },
  { influencer: 'MayaSkincare', spend: 12000, reach: 185000, clicks: 7200, conversions: 98, revenue: 45600, roas: 3.8, cpa: 122, performance: 'excellent' as const },
  { influencer: 'RiyaStyle', spend: 31000, reach: 290000, clicks: 5400, conversions: 48, revenue: 27900, roas: 0.9, cpa: 646, performance: 'needs_attention' as const },
  { influencer: 'KabirWellness', spend: 7000, reach: 95000, clicks: 2100, conversions: 22, revenue: 18200, roas: 2.6, cpa: 318, performance: 'healthy' as const },
]

export const approvals: ApprovalItem[] = [
  {
    id: 'ap-1',
    agent: 'Optimization Agent',
    type: 'budget',
    action: 'Reallocate ₹10,000 campaign budget',
    reason: 'RiyaStyle is underperforming while NehaBeauty and AditiBeauty are exceeding target ROAS.',
    campaign: 'GlowNaturals Summer Launch',
    financialImpact: '+₹34K expected revenue',
    confidence: 86,
    timestamp: '12 min ago',
    status: 'pending',
  },
  {
    id: 'ap-2',
    agent: 'Outreach Agent',
    type: 'outreach',
    action: 'Approve personalized message to @AditiBeauty',
    reason: 'Message personalized from skincare content history and audience demographics.',
    campaign: 'GlowNaturals Summer Launch',
    financialImpact: '₹22K estimated collab',
    confidence: 92,
    timestamp: '28 min ago',
    status: 'pending',
  },
  {
    id: 'ap-3',
    agent: 'Outreach Agent',
    type: 'negotiation',
    action: 'Counteroffer ₹26,000 to @RiyaStyle',
    reason: 'Creator quoted ₹35K vs historical avg ₹24K. Recommended counter preserves target ROAS.',
    campaign: 'GlowNaturals Summer Launch',
    financialImpact: 'ROAS 2.4x vs 1.7x at quote',
    confidence: 88,
    timestamp: '1 hr ago',
    status: 'pending',
  },
  {
    id: 'ap-4',
    agent: 'Contract Agent',
    type: 'contract',
    action: 'Flag exclusivity clause risk',
    reason: 'Contract does not specify reshoot obligations and posting deadline is tight.',
    campaign: 'GlowNaturals Summer Launch',
    financialImpact: '₹26K contract value',
    confidence: 90,
    timestamp: '2 hr ago',
    status: 'pending',
  },
  {
    id: 'ap-5',
    agent: 'Strategy Agent',
    type: 'campaign',
    action: 'Approve creator mix for Men\'s Skincare Pilot',
    reason: 'Recommended 6 micro + 2 mid-tier creators for awareness objective.',
    campaign: 'Men\'s Skincare Pilot',
    financialImpact: '₹80K budget plan',
    confidence: 85,
    timestamp: '3 hr ago',
    status: 'pending',
  },
]

export const approvalHistory: ApprovalItem[] = [
  {
    id: 'ah-1',
    agent: 'Discovery Agent',
    type: 'campaign',
    action: 'Approved shortlist of 6 creators',
    reason: 'Strong audience coverage within budget.',
    campaign: 'GlowNaturals Summer Launch',
    financialImpact: '₹1.42L expected spend',
    confidence: 93,
    timestamp: 'Yesterday',
    status: 'approved',
  },
  {
    id: 'ah-2',
    agent: 'Outreach Agent',
    type: 'outreach',
    action: 'Sent outreach to @NehaBeauty',
    reason: 'Message approved after minor edit.',
    campaign: 'GlowNaturals Summer Launch',
    financialImpact: '₹18K estimated collab',
    confidence: 95,
    timestamp: '2 days ago',
    status: 'edited',
  },
]

export const contracts: Contract[] = [
  {
    id: 'ct-1',
    creator: 'Aditi Sharma',
    username: 'aditibeauty',
    campaign: 'GlowNaturals Summer Launch',
    value: 26000,
    status: 'signed',
    startDate: '2026-08-22',
    endDate: '2026-09-15',
    paymentDue: '2026-09-20',
    risk: 'Low',
    deliverables: ['2 Instagram Reels', '3 Stories'],
    usageRights: '90 days',
    exclusivity: '30 days',
    aiRisks: [
      'Posting deadline is 4 days before campaign end.',
      'Contract does not specify reshoot obligations.',
    ],
  },
  {
    id: 'ct-2',
    creator: 'Neha Kapoor',
    username: 'NehaBeauty',
    campaign: 'GlowNaturals Summer Launch',
    value: 18000,
    status: 'signed',
    startDate: '2026-08-21',
    endDate: '2026-09-18',
    paymentDue: '2026-09-22',
    risk: 'Low',
    deliverables: ['3 Instagram Reels', '5 Stories', '1 Feed post'],
    usageRights: '120 days',
    exclusivity: '45 days',
    aiRisks: [],
  },
  {
    id: 'ct-3',
    creator: 'Sara Ali',
    username: 'saraglows',
    campaign: 'GlowNaturals Summer Launch',
    value: 38000,
    status: 'pending_signature',
    startDate: '2026-08-25',
    endDate: '2026-09-20',
    paymentDue: '2026-09-25',
    risk: 'Medium',
    deliverables: ['4 TikTok videos', '2 Instagram Reels'],
    usageRights: '90 days',
    exclusivity: '30 days',
    aiRisks: ['Awaiting creator signature for 3 days.'],
  },
  {
    id: 'ct-4',
    creator: 'Maya Chen',
    username: 'mayaskincare',
    campaign: 'Vitamin C Serum Awareness',
    value: 12000,
    status: 'at_risk',
    startDate: '2026-07-20',
    endDate: '2026-08-20',
    paymentDue: '2026-08-25',
    risk: 'High',
    deliverables: ['2 Instagram Reels'],
    usageRights: '60 days',
    exclusivity: '15 days',
    aiRisks: ['Payment overdue by 5 days.', 'One deliverable still pending.'],
  },
  {
    id: 'ct-5',
    creator: 'Kabir Jain',
    username: 'kabirwellness',
    campaign: 'Festive Glow Collection',
    value: 45000,
    status: 'expired',
    startDate: '2026-06-01',
    endDate: '2026-07-01',
    paymentDue: '2026-07-05',
    risk: 'Low',
    deliverables: ['1 YouTube video', '2 Shorts'],
    usageRights: '180 days',
    exclusivity: '60 days',
    aiRisks: [],
  },
]

export const notifications: NotificationItem[] = [
  {
    id: 'n1',
    type: 'agent',
    title: 'Strategy Agent finished campaign planning',
    body: 'Summer Launch strategy is ready for your review.',
    timestamp: '5 min ago',
    read: false,
    actionLabel: 'View Strategy',
  },
  {
    id: 'n2',
    type: 'approval',
    title: '3 influencer messages require approval',
    body: 'Outreach Agent prepared drafts awaiting human approval.',
    timestamp: '18 min ago',
    read: false,
    actionLabel: 'Review',
  },
  {
    id: 'n3',
    type: 'contract',
    title: 'Contract with @AditiBeauty expires in 4 days',
    body: 'Usage rights window ends on Sep 15.',
    timestamp: '1 hr ago',
    read: false,
    actionLabel: 'View Contract',
  },
  {
    id: 'n4',
    type: 'performance',
    title: 'Campaign ROAS dropped below 2x',
    body: 'Clean Beauty UGC Drive currently at 0.9x ROAS.',
    timestamp: '2 hr ago',
    read: true,
    actionLabel: 'Open Analytics',
  },
  {
    id: 'n5',
    type: 'budget',
    title: 'Budget reallocation recommended',
    body: 'Optimization Agent proposes moving ₹10,000 from RiyaStyle.',
    timestamp: '3 hr ago',
    read: true,
    actionLabel: 'Review',
  },
  {
    id: 'n6',
    type: 'campaign',
    title: 'GlowNaturals Summer Launch is 64% complete',
    body: '5 creators live, 2 completed deliverables.',
    timestamp: 'Yesterday',
    read: true,
  },
]

export const optimizations: OptimizationRec[] = [
  {
    id: 'opt-1',
    title: 'Budget Reallocation',
    current: { creator: 'RiyaStyle', remaining: 18000, roas: 0.9 },
    moves: [
      { to: 'NehaBeauty', amount: 6000 },
      { to: 'AditiBeauty', amount: 4000 },
    ],
    expectedRevenue: '₹31,000–₹38,000',
    confidence: 86,
    status: 'pending',
  },
]

export const performanceInsights: Insight[] = [
  {
    id: 'pi-1',
    title: 'High-efficiency creator',
    body: 'NehaBeauty has generated 4.1x ROAS with only 12% of campaign spend.',
    impact: 'Scale allocation',
    confidence: 94,
    action: 'Increase budget',
    type: 'opportunity',
  },
  {
    id: 'pi-2',
    title: 'Underperformer alert',
    body: "RiyaStyle's conversion rate is 47% below the campaign average.",
    impact: 'Protect budget',
    confidence: 91,
    action: 'Reduce allocation',
    type: 'warning',
  },
  {
    id: 'pi-3',
    title: 'Winning content format',
    body: 'Instagram Reels account for 71% of campaign-generated revenue.',
    impact: 'Format priority',
    confidence: 89,
    action: 'Brief creators',
    type: 'info',
  },
]

export const platformPerformance = [
  { platform: 'Instagram', spend: 82000, revenue: 278000, roas: 3.39 },
  { platform: 'YouTube', spend: 28000, revenue: 62000, roas: 2.21 },
  { platform: 'TikTok', spend: 18000, revenue: 52000, roas: 2.89 },
]

export const roasOverTime = [
  { date: 'Week 1', roas: 1.8 },
  { date: 'Week 2', roas: 2.2 },
  { date: 'Week 3', roas: 2.6 },
  { date: 'Week 4', roas: 2.9 },
  { date: 'Week 5', roas: 3.06 },
]

export const conversionsOverTime = [
  { date: 'Week 1', conversions: 42 },
  { date: 'Week 2', conversions: 78 },
  { date: 'Week 3', conversions: 124 },
  { date: 'Week 4', conversions: 186 },
  { date: 'Week 5', conversions: 426 },
]

export const outreachMessage = `Hi Aditi,

I've been following your skincare content — especially your recent vitamin C routine series — and loved how clearly you break down ingredient benefits for your audience.

We're launching GlowNaturals' Summer Serum collection and think you'd be a fantastic partner. Your audience demographics align closely with our target (women 25–34 interested in clean beauty), and we'd love to collaborate on 2 Reels + 3 Stories.

Happy to share the full brief and discuss rates that work for you.

Looking forward to creating something beautiful together.

Best,
Aaditya
GlowNaturals Marketing`

export const reports = [
  { id: 'r1', name: 'Campaign Performance Report', description: 'Full funnel metrics, spend, and ROAS by campaign.' },
  { id: 'r2', name: 'Influencer Performance Report', description: 'Creator-level reach, conversions, and efficiency.' },
  { id: 'r3', name: 'ROI Analysis', description: 'Budget utilization and incremental revenue analysis.' },
  { id: 'r4', name: 'Executive Summary', description: 'Board-ready overview of campaign outcomes.' },
  { id: 'r5', name: 'Contract Status Report', description: 'Signatures, deliverables, and payment timelines.' },
  { id: 'r6', name: 'AI Optimization History', description: 'All optimization recommendations and outcomes.' },
]
